//
//  FilterType.swift
//  BBMetalImageDemo
//
//  Created by Kaibo Lu on 4/10/19.
//  Copyright © 2019 Kaibo Lu. All rights reserved.
//

enum FilterType {
    case brightness
    case exposure
    case contrast
    case saturation
    case gamma
    case levels
    case colorMatrix
    case rgba
    case hue
    case vibrance
    case whiteBalance
    case highlightShadow
    case highlightShadowTint
    case lookup
    case colorInversion
    case monochrome
    case falseColor
    case haze
    case luminance
    case luminanceThreshold
    case erosion
    case rgbaErosion
    case dilation
    case rgbaDilation
    case chromaKey
    case crop
    case resize
    case rotate
    case flip
    case transform
    case sharpen
    case unsharpMask
    case gaussianBlur
    case boxBlur
    case zoomBlur
    case motionBlur
    case tiltShift
    case normalBlend
    case chromaKeyBlend
    case dissolveBlend
    case addBlend
    case subtractBlend
    case multiplyBlend
    case divideBlend
    case overlayBlend
    case darkenBlend
    case lightenBlend
    case colorBlend
    case colorBurnBlend
    case colorDodgeBlend
    case screenBlend
    case exclusionBlend
    case differenceBlend
    case hardLightBlend
    case softLightBlend
    case alphaBlend
    case sourceOverBlend
    case hueBlend
    case saturationBlend
    case luminosityBlend
    case linearBurnBlend
    case maskBlend
    case pixellate
    case polarPixellate
    case polkaDot
    case halftone
    case crosshatch
    case sketch
    case thresholdSketch
    case toon
    case posterize
    case vignette
    case kuwahara
    case swirl
    case bulge
    case pinch
    case convolution3x3
    case emboss
    case sobelEdgeDetection
    case bilateralBlur
    case beauty
}
